### ISSUE TITLE
Add feature to support mutiple environment resources at same time

### ISSUE THREAD

**Issue by briantward** [cptmorgan-rh/openshift4_vcenter_permissions#1]
Would be nice to be able to grant access to multiple datacenter, datastore, switch, portgroup, folders, etc

**Comment by briantward** [comment]
e.g. 

```
vcenter:
...
  environments:
  - name: lab
    datacenter: dc0
    cluster: LAB
    datastore: ds0
    network: 10.0.0.x-24
    folder: openshift4-lab
  - name: dev
    datacenter: dc0
    cluster: DEV
    datastore: ds3
    network: 10.0.1.x-24
    folder: openshift4-dev
```
